# 1. PyTorch Tensor Shape Convention

## 1.1 2D Tensor(Typical Computer Vision)

|t| = (batchsize, dim) # 세로, 가로

## 1.2 3D Tensor(Typical Computer Vision)

|t| = (batchsize, width, height) # 세로, 가로, 깊이

## 1.3 3D Tensor(Typical Natural Language Processing)

|t| = (batch size, length, dim) # 세로, 가로, 깊이 # 자연어의 경우 : 가로 * 깊이 의 너비만큼 문장이 존재함


In [3]:
import numpy as np
import torch

# 2. Numpy Review

## 2.1 1D Array with Numpy

In [6]:
t = np.array([0., 1., 2., 3., 4., 5., 6.])

# ndim : 차원 확인
print('Rank of t : ', t.ndim)

# shape : 형태 확인
print('Shape of t : ', t.shape)

# [] : element 추출
print('t[0] t[1] t[-1] = ', t[0], t[1], t[-1]) 

# [:] : slicing하여 1개 이상의 원소 추출
print('t[2:5] t[4:-1]  = ', t[2:5], t[4:-1])   
print('t[:2] t[3:]     = ', t[:2], t[3:])     

Rank of t :  1
Shape of t :  (7,)
t[0] t[1] t[-1] =  0.0 1.0 6.0
t[2:5] t[4:-1]  =  [2. 3. 4.] [4. 5.]
t[:2] t[3:]     =  [0. 1.] [3. 4. 5. 6.]


## 2.2 2D Array with Numpy

In [8]:
t = np.array([[1., 2., 3.], [4., 5., 6.], [7., 8., 9.], [10., 11., 12.]])
print(t)

# ndim : 차원 확인
print('Rank  of t: ', t.ndim)

# shape : 형태 확인
print('Shape of t: ', t.shape)

[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]
 [10. 11. 12.]]
Rank  of t:  2
Shape of t:  (4, 3)


# 3. PyTorch Tensor

## 3.1 1D Array with PyTorch

In [9]:
t = torch.FloatTensor([0., 1., 2., 3., 4., 5., 6.])
print(t)

# dim : rank
print(t.dim())

# shape, size는 같은 역할
print(t.shape)  
print(t.size()) 

# 데이터 추출
print(t[0], t[1], t[-1])  # Element
print(t[2:5], t[4:-1])    # Slicing
print(t[:2], t[3:])       # Slicing

tensor([0., 1., 2., 3., 4., 5., 6.])
1
torch.Size([7])
torch.Size([7])
tensor(0.) tensor(1.) tensor(6.)
tensor([2., 3., 4.]) tensor([4., 5.])
tensor([0., 1.]) tensor([3., 4., 5., 6.])


## 3.2 2D Array with PyTorch

In [14]:
t = torch.FloatTensor([[1., 2., 3.],
                       [4., 5., 6.],
                       [7., 8., 9.],
                       [10., 11., 12.]
                      ])
print(t)

# rank
print(t.dim())  

# shape, size는 같은 역할
print(t.shape)
print(t.size())

# 데이터 추출
print(t[:, 1])
print(t[:, 1].size())
print(t[:, :-1])

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])
2
torch.Size([4, 3])
torch.Size([4, 3])
tensor([ 2.,  5.,  8., 11.])
torch.Size([4])
tensor([[ 1.,  2.],
        [ 4.,  5.],
        [ 7.,  8.],
        [10., 11.]])


# 4. Frequently Used Operations in PyTorch

## 4.1 Broadcasting

In [24]:
# same shape
m1 = torch.FloatTensor([[3, 3]])
m2 = torch.FloatTensor([[2, 2]])
print(m1 + m2)

# vector + scalar
m1 = torch.FloatTensor([[1, 2]])
m2 = torch.FloatTensor([3]) # 3 -> [[3, 3]]
print(m1 + m2)

# 2 x 1 vector + 1 x 2 vector
m1 = torch.FloatTensor([[1, 2]])
m2 = torch.FloatTensor([[3], [4]])
print(m1 + m2)

tensor([[5., 5.]])
tensor([[4., 5.]])
tensor([[4., 5.],
        [5., 6.]])


## 4.2 Mul vs Matmul

In [21]:
m1 = torch.FloatTensor([[1, 2], [3, 4]]) # 2 x 2
m2 = torch.FloatTensor([[1], [2]])  # 2 x 1

print('shape of Matrix 1 : ' , m1.shape)
print('shape of Matrix 2 : ' , m2.shape)

print(m1.matmul(m2)) # 2 x 1

# broadcasting이 일어나면서 각각의 element끼리 곱해져요
print(m1 * m2) # 2 x 2
print(m1.mul(m2))

shape of Matrix 1 :  torch.Size([2, 2])
shape of Matrix 2 :  torch.Size([2, 1])
tensor([[ 5.],
        [11.]])
tensor([[1., 2.],
        [6., 8.]])
tensor([[1., 2.],
        [6., 8.]])


## 4.3 Mean

In [25]:
t = torch.FloatTensor([1, 2])
print(t.mean())

tensor(1.5000)


In [26]:
# can't use mean() on integers
t = torch.LongTensor([1, 2])
try : 
    print(t.mean())
except Exception as exc :
    print(exc)

Can only calculate the mean of floating types. Got Long instead.


In [29]:
t = torch.FloatTensor([[1, 2], [3, 4]])
print(t)

print(t.mean())

# 차원에 대한 평균 구하기
print(t.mean(dim=0))
print(t.mean(dim=1))
print(t.mean(dim=-1))

tensor([[1., 2.],
        [3., 4.]])
tensor(2.5000)
tensor([2., 3.])
tensor([1.5000, 3.5000])
tensor([1.5000, 3.5000])


## 4.4 Sum

In [30]:
t = torch.FloatTensor([[1, 2], [3, 4]])
print(t)

print(t.sum())

# 차원에 대한 합 구하기
print(t.sum(dim=0)) # 1 + 3, 2 + 4
print(t.sum(dim=1)) # 1 + 2, 3 + 4
print(t.sum(dim=-1)) # 1 + 2, 3 + 4

tensor([[1., 2.],
        [3., 4.]])
tensor(10.)
tensor([4., 6.])
tensor([3., 7.])
tensor([3., 7.])


## 4.5 Max, Argmax

In [38]:
t = torch.FloatTensor([[1, 2], [3, 4]])
print(t)

# 데이터 전체 중 최대값
print(t.max())

# 각 차원 중 최대 값
print(t.max(dim=0))

# max, argmax
print()
print('Max: ', t.max(dim=0)[0])
print('Argmax: ', t.max(dim=0)[1])

print()
print(t.max(dim=1))
print(t.max(dim=-1))

tensor([[1., 2.],
        [3., 4.]])
tensor(4.)
torch.return_types.max(
values=tensor([3., 4.]),
indices=tensor([1, 1]))

Max:  tensor([3., 4.])
Argmax:  tensor([1, 1])

torch.return_types.max(
values=tensor([2., 4.]),
indices=tensor([1, 1]))
torch.return_types.max(
values=tensor([2., 4.]),
indices=tensor([1, 1]))


## 4.6 View, Reshape

In [39]:
t = np.array([[[0, 1, 2],
              [3, 4, 5]],
             [[6, 7, 8],
             [9, 10, 11]]])

ft = torch.FloatTensor(t)
print(ft.shape)

torch.Size([2, 2, 3])


In [41]:
# ( 2, 2, 3) = ( 2 x 2, 3) = (4 , 3)
# -1을 제외한 shape에 기준을 둡니다.
print(ft.view([-1, 3]))
print(ft.view([-1, 3]).shape)
# 3개의 열을 무조건 가지고 => 나머지 tensor를 알아서 배열합니다.

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])
torch.Size([4, 3])


In [42]:
print(ft.view([-1, 1, 3]))
print(ft.view([-1, 1, 3]).shape)

tensor([[[ 0.,  1.,  2.]],

        [[ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.]],

        [[ 9., 10., 11.]]])
torch.Size([4, 1, 3])


## 4.7 Squeeze

In [48]:
ft = torch.FloatTensor([[0], [1], [2]])
print(ft)
print(ft.shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


In [55]:
# squeeze :  한 차원 낮춰준다
print(ft.squeeze(dim = 0))
print(ft.squeeze().shape)

print(ft.squeeze(dim = 1))
print(ft.squeeze().shape)

# default
print(ft.squeeze())
print(ft.squeeze().shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3])
tensor([0., 1., 2.])
torch.Size([3])
tensor([0., 1., 2.])
torch.Size([3])


## 4.8 Unsqueeze

In [56]:
ft = torch.Tensor([0, 1, 2])
print(ft.shape)

torch.Size([3])


In [58]:
# unsqueeze : 한 차원 올려준다
print(ft.unsqueeze(0))
print(ft.unsqueeze(0).shape)

tensor([[0., 1., 2.]])
torch.Size([1, 3])


In [59]:
print(ft.view(1, -1))
print(ft.view(1, -1).shape)

tensor([[0., 1., 2.]])
torch.Size([1, 3])


In [60]:
print(ft.unsqueeze(1))
print(ft.unsqueeze(1).shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


In [61]:
print(ft.unsqueeze(-1))
print(ft.unsqueeze(-1).shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


## 4.9 Casting

In [62]:
lt = torch.LongTensor([1, 2, 3, 4])
print(lt)
print(lt.float())

bt = torch.ByteTensor([True, False, False, True])
print(bt)
print(bt.long())
print(bt.float())

tensor([1, 2, 3, 4])
tensor([1., 2., 3., 4.])
tensor([1, 0, 0, 1], dtype=torch.uint8)
tensor([1, 0, 0, 1])
tensor([1., 0., 0., 1.])


## 4.10 Concatenation

In [63]:
x = torch.FloatTensor([[1, 2], [3, 4]])
y = torch.FloatTensor([[5, 6], [7, 8]])

print(torch.cat([x, y], dim=0)) # 행으로 병합
print(torch.cat([x, y], dim=1)) # 열로 병합

tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]])
tensor([[1., 2., 5., 6.],
        [3., 4., 7., 8.]])


## 4.11 Stacking

In [64]:
x = torch.FloatTensor([1, 4])
y = torch.FloatTensor([2, 5])
z = torch.FloatTensor([3, 6])

In [65]:
# stack default dim = 0
# concat과 다르게 새로운 차원 안에 데이터를 쌓아요
print(torch.stack([x, y, z])) 
print(torch.stack([x, y, z], dim=1))

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])
tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [66]:
print(torch.cat([x.unsqueeze(0), y.unsqueeze(0), z.unsqueeze(0)], dim=0))

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])


## 4.12 Ones and Zeros

In [68]:
x = torch.FloatTensor([[0, 1, 2],
                       [2, 1, 0]])

# x와 같은 shape이면서 1 또는 0의 값을 갖는 tensor가 생성됩니다
print(torch.ones_like(x))
print(torch.zeros_like(x))

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])


## 4.13 In-place Operation

In [69]:
x = torch.FloatTensor([[1, 2], [3, 4]])
print(x.mul(2.))
print(x)

# x.mul에 _를 붙이면 메모리에 새롭게 선언하지 않고 결과값을 tensor에 넣게됩니다
print(x.mul_(2.))
print(x)

tensor([[2., 4.],
        [6., 8.]])
tensor([[1., 2.],
        [3., 4.]])
tensor([[2., 4.],
        [6., 8.]])
tensor([[2., 4.],
        [6., 8.]])


## 4.14 zip

In [70]:
# 함께 순서를 세어나가요

for x, y in zip([1, 2, 3], [4, 5, 6]):
    print(x, y)
    
for x, y, z in zip([1, 2, 3], [4, 5, 6], [7, 8, 9]):
    print(x, y, z)

1 4
2 5
3 6
1 4 7
2 5 8
3 6 9
